indent_style = "block"
# use_small_heuristics
binop_separator = "Front"
combine_control_expr = false
comment_width = 120
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
disable_all_formatting = false
error_on_line_overflow = true
error_on_unformatted = true
fn_args_density = "Tall"
brace_style = "SameLineWhere"
empty_item_single_line = true
enum_discrim_align_threshold = 0
fn_single_line = false
where_single_line = true
force_explicit_abi = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
hard_tabs = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
merge_imports = false
match_block_trailing_comma = true
max_width = 120
merge_derives = true
force_multiline_blocks = true
newline_style = "Unix"
normalize_comments = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
report_todo = "Never"
report_fixme = "Never"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 0
spaces_around_ranges = false
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = true
struct_lit_single_line = true
wrap_comments = true
match_arm_blocks = true
overflow_delimited_expr = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
# required_version
hide_parse_errors = true
color = "Auto"
unstable_features = true
# license_template_path = ""
normalize_doc_attributes = true
inline_attribute_width = 0
